kind: pipeline
name: documentation

steps:
  - name: build-docs
    image: node:alpine
    commands:
      - apk add --no-cache git
      - ./scripts/set-github-ci.sh
      - ./scripts/deploy-documentation.sh
    environment:
      GH_TOKEN:
        from_secret: GH_TOKEN
      GH_USER:
        from_secret: GH_USER
    when:
      branch: master

---
kind: pipeline
name: application

steps:
  - name: build-app
    image: plugins/docker
    settings:
      repo: platyplus/platyplus
      target: production-stage
      tags: latest
      username:
        from_secret: DH_USER
      password:
        from_secret: DH_PASSWORD
