kind: pipeline
name: documentation

steps:
  - name: build-docs
    image: node:alpine
    commands:
      - apk add --no-cache git
      - ./scripts/set-github-ci.sh
      - ./scripts/deploy-documentation.sh
    environment:
      GH_TOKEN:
        from_secret: GH_TOKEN
      GH_USER:
        from_secret: GH_USER
    when:
      branch: master

---
kind: pipeline
name: authentication-build
steps:
  - name: build-auth-service
    image: plugins/docker
    settings:
      context: services/authentication
      dockerfile: services/authentication/Dockerfile
      repo: platyplus/authentication
      tags: latest
      username:
        from_secret: DH_USER
      password:
        from_secret: DH_PASSWORD

---
kind: pipeline
name: graphql-engine-build
steps:
  - name: pre-build-graphql-service
    image: alpine
    commands: # TODO: set the migrations in the services/graphql-engine directory, an update the script/location of the hasura project
      - cp -R migrations services/graphql-engine/
  - name: build-graphql-service
    image: plugins/docker
    settings:
      context: services/graphql-engine
      dockerfile: services/graphql-engine/Dockerfile
      repo: platyplus/graphql-engine
      tags: latest
      username:
        from_secret: DH_USER
      password:
        from_secret: DH_PASSWORD

---
kind: pipeline
name: application-build
steps:
  - name: build-application
    image: plugins/docker
    settings:
      dockerfile: server/Dockerfile
      repo: platyplus/platyplus
      target: production-stage
      tags: latest
      username:
        from_secret: DH_USER
      password:
        from_secret: DH_PASSWORD

---
kind: pipeline
name: synchronization-hook-build
steps:
  - name: build-sync-hook
    image: plugins/docker
    settings:
      context: services/synchronization-hook
      dockerfile: services/synchronization-hook/Dockerfile
      repo: platyplus/synchronization-hook
      tags: latest
      username:
        from_secret: DH_USER
      password:
        from_secret: DH_PASSWORD
