kind: pipeline
name: default

steps:
  - name: build-docs
    image: node:alpine
    commands:
      - apk add --no-cache git
      - npm install
      - npm run docs:build
      - cd docs/.vuepress/dist
      - ls && git commit -m 'deploy'
      - git push -u origin master
    when:
      branch: master
