version: '3.1'
services:
  reverse-proxy:
    command:
      - '--docker.watch'
  authentication:
    environment:
      NODE_ENV: production
      HASURA_GRAPHQL_ACCESS_KEY_FILE: /run/secrets/hasura_secret_key
      PUBLIC_KEY_FILE: /run/secrets/authentication_public_key
      PRIVATE_KEY_FILE: /run/secrets/authentication_private_key
    secrets:
      - hasura_secret_key
      - authentication_public_key
      - authentication_private_key
    deploy:
      replicas: 2
  graphql-engine:
    environment:
      HASURA_GRAPHQL_ACCESS_KEY_FILE: /run/secrets/hasura_secret_key
      AUTH_PUBLIC_KEY_FILE: /run/secrets/authentication_public_key
    depends_on:
      - 'authentication' # TODO: https://github.com/jwilder/dockerize -wait
    secrets:
      - hasura_secret_key
      - authentication_public_key
    deploy:
      replicas: 2
secrets:
  hasura_secret_key:
    external: true
  authentication_public_key:
    external: true
  authentication_private_key:
    external: true
