version: '3.1'
services:
  reverse-proxy:
    image: traefik # The official Traefik docker image
    command:
      - '--api'
      - '--docker'
      - '--web'
    ports:
      - '80:80' # The HTTP port
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    healthcheck:
      test: ['CMD', '/traefik', 'healthcheck', '--ping']
      interval: 30s
      timeout: 5s
  postgres:
    image: mdillon/postgis:11-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 30s
      timeout: 5s
  authentication:
    image: platyplus/authentication
    depends_on:
      - 'postgres' # TODO: https://github.com/jwilder/dockerize -wait
    environment:
      HASURA_URL: 'http://graphql-engine:3000/v1alpha1/graphql'
      ALGORITHM: 'RS256'
  graphql-engine:
    image: platyplus/graphql-engine
    labels:
      - 'traefik.frontend.rule=Host:graphql.${DOMAIN}'
      - 'traefik.port=3000'
    depends_on:
      - 'postgres' # TODO: https://github.com/jwilder/dockerize -wait
      - 'authentication'
    environment:
      HASURA_GRAPHQL_SERVER_PORT: 3000
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: '${HASURA_ENABLE_CONSOLE:-true}'
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: 'anonymous'
      AUTH_ALGORITHM: RS256
  app:
    image: platyplus/platyplus
    labels:
      - 'traefik.frontend.rule=Host:app.${DOMAIN}'
      - 'traefik.port=80'
    depends_on:
      - 'graphql-engine'
    environment:
      API: 'graphql.${DOMAIN}/v1alpha1/graphql'
  synchronization-hook:
    image: platyplus/synchronization-hook
    depends_on:
      - 'graphql-engine' # TODO: https://github.com/jwilder/dockerize -wait
volumes:
  db_data:
