version: '3.1'
services:
  authentication:
    deploy:
      replicas: 1
    environment:
      HASURA_GRAPHQL_ACCESS_KEY_FILE: /run/secrets/hasura_secret_key
      NODE_ENV: production
      PRIVATE_KEY_FILE: /run/secrets/authentication_private_key
      PUBLIC_KEY_FILE: /run/secrets/authentication_public_key
    secrets:
      - authentication_private_key
      - authentication_public_key
      - hasura_secret_key
  administration:
    deploy:
      replicas: 1
    environment:
      HASURA_GRAPHQL_ACCESS_KEY_FILE: /run/secrets/hasura_secret_key
      NODE_ENV: production
      PUBLIC_KEY_FILE: /run/secrets/authentication_public_key
    secrets:
      - authentication_public_key
      - hasura_secret_key
  graphql-engine:
    deploy:
      replicas: 1
    environment:
      AUTH_PUBLIC_KEY_FILE: /run/secrets/authentication_public_key
      HASURA_GRAPHQL_ACCESS_KEY_FILE: /run/secrets/hasura_secret_key
    secrets:
      - authentication_public_key
      - hasura_secret_key
  reverse-proxy:
    command:
      - '--docker.watch'
  synchronization-hook:
    deploy:
      replicas: 1
    environment:
      HASURA_GRAPHQL_ACCESS_KEY_FILE: /run/secrets/hasura_secret_key
      NODE_ENV: production
    secrets:
      - hasura_secret_key
secrets:
  authentication_private_key:
    external: true
  authentication_public_key:
    external: true
  hasura_secret_key:
    external: true
