version: '3.4'
services:
  app:
    image: platyplus/platyplus-service
    depends_on:
      - graphql-engine
    environment:
      API: 'graphql.${DOMAIN}/v1/graphql'
    labels:
      - 'traefik.frontend.rule=Host:app.${DOMAIN}'
      - traefik.port=3000
  authentication:
    image: platyplus/authentication-service
    environment:
      HASURA_URL: 'http://graphql-engine:3000'
      HASURA_GRAPHQL_ADMIN_SECRET_FILE: /run/secrets/hasura_secret_key
      NODE_ENV: production
      PRIVATE_KEY_FILE: /run/secrets/authentication_private_key
      PUBLIC_KEY_FILE: /run/secrets/authentication_public_key
    deploy:
      replicas: 1
    secrets:
      - authentication_private_key
      - authentication_public_key
      - hasura_secret_key
  functions:
    image: platyplus/functions-service
    environment:
      HASURA_URL: 'http://graphql-engine:3000'
      POSTGRES_URL: 'postgresql://postgres@postgres/postgres'
      NODE_ENV: production
      HASURA_GRAPHQL_ADMIN_SECRET_FILE: /run/secrets/hasura_secret_key
      PUBLIC_KEY_FILE: /run/secrets/authentication_public_key
    deploy:
      replicas: 1
    secrets:
      - authentication_public_key
      - hasura_secret_key
  graphql-engine:
    image: platyplus/graphql-engine
    depends_on:
      - authentication
      - postgres
    environment:
      EVENTS_URL: 'http://functions:3000/events'
      AUTH_URL: 'http://authentication:3000/graphql'
      HASURA_GRAPHQL_ADMIN_SECRET_FILE: /run/secrets/hasura_secret_key
    labels:
      - 'traefik.frontend.rule=Host:graphql.${DOMAIN}'
      - traefik.port=3000
    deploy:
      replicas: 1
    secrets:
      - authentication_public_key
      - hasura_secret_key
  postgres:
    image: 'mdillon/postgis:11-alpine'
    volumes:
      - 'db_data:/var/lib/postgresql/data'
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U postgres
      interval: 30s
      timeout: 5s
  reverse-proxy:
    image: traefik
    command:
      - '--docker.watch'
      - '--docker'
      - '--web'
    ports:
      - '80:80'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
    healthcheck:
      test:
        - CMD
        - /traefik
        - healthcheck
        - '--ping'
      interval: 30s
      timeout: 5s
volumes:
  db_data: null
secrets:
  authentication_private_key:
    external: true
  authentication_public_key:
    external: true
  hasura_secret_key:
    external: true
