version: '3.1'
services:
  reverse-proxy:
    image: traefik
    command:
      - '--docker.watch'
      - '--docker'
    ports:
      - '80:80'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
  postgres:
    image: 'mdillon/postgis:11-alpine'
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U postgres
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - 'db_data:/var/lib/postgresql/data'
  authentication:
    image: platyplus/authentication
    depends_on:
      - postgres
    environment:
      ALGORITHM: RS256
      HASURA_URL: 'http://graphql-engine:8080/v1alpha1/graphql'
      NODE_ENV: production
      HASURA_GRAPHQL_ACCESS_KEY_FILE: /run/secrets/hasura_secret_key
      PUBLIC_KEY_FILE: /run/secrets/authentication_public_key
      PRIVATE_KEY_FILE: /run/secrets/authentication_private_key
    secrets:
      - hasura_secret_key
      - authentication_public_key
      - authentication_private_key
    deploy:
      replicas: 2
  graphql-engine:
    image: platyplus/graphql-engine
    labels:
      - 'traefik.frontend.rule=Host:graphql.${DOMAIN}'
      - traefik.port=8080
    depends_on:
      - authentication
    environment:
      HASURA_GRAPHQL_DATABASE_URL: 'postgres://postgres:@postgres:5432/postgres'
      HASURA_GRAPHQL_ENABLE_CONSOLE: '${HASURA_ENABLE_CONSOLE:-true}'
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: anonymous
      AUTH_ALGORITHM: RS256
      HASURA_GRAPHQL_ACCESS_KEY_FILE: /run/secrets/hasura_secret_key
      AUTH_PUBLIC_KEY_FILE: /run/secrets/authentication_public_key
    secrets:
      - hasura_secret_key
      - authentication_public_key
    deploy:
      replicas: 2
  app:
    image: platyplus/platyplus
    labels:
      - 'traefik.frontend.rule=Host:app.${DOMAIN}'
      - traefik.port=80
    depends_on:
      - authentication
      - graphql-engine
    environment:
      API: 'graphql.${DOMAIN}/v1alpha1/graphql'
volumes:
  db_data: null
secrets:
  hasura_secret_key:
    external: true
  authentication_public_key:
    external: true
  authentication_private_key:
    external: true
