version: '3.4'
services:
  app:
    image: platyplus/platyplus
    depends_on:
      - graphql-engine
    environment:
      API: 'api.${DOMAIN}'
    labels:
      - 'traefik.frontend.rule=Host:app.${DOMAIN}'
      - traefik.port=3000
  administration:
    image: platyplus/administration
    environment:
      HASURA_URL: 'http://graphql-engine:3000/v1alpha1/graphql'
      HASURA_GRAPHQL_ADMIN_SECRET_FILE: /run/secrets/hasura_secret_key
      NODE_ENV: production
      PUBLIC_KEY_FILE: /run/secrets/authentication_public_key
    deploy:
      replicas: 1
    secrets:
      - authentication_public_key
      - hasura_secret_key
  authentication:
    image: platyplus/authentication
    environment:
      HASURA_URL: 'http://graphql-engine:3000/v1alpha1/graphql'
      HASURA_GRAPHQL_ADMIN_SECRET_FILE: /run/secrets/hasura_secret_key
      NODE_ENV: production
      PRIVATE_KEY_FILE: /run/secrets/authentication_private_key
      PUBLIC_KEY_FILE: /run/secrets/authentication_public_key
    deploy:
      replicas: 1
    secrets:
      - authentication_private_key
      - authentication_public_key
      - hasura_secret_key
  functions:
    image: platyplus/functions
    environment:
      HASURA_URL: 'http://graphql-engine:3000/v1alpha1/graphql'
      NODE_ENV: production
      HASURA_GRAPHQL_ADMIN_SECRET_FILE: /run/secrets/hasura_secret_key
      PUBLIC_KEY_FILE: /run/secrets/authentication_public_key
    deploy:
      replicas: 1
    secrets:
      - authentication_public_key
      - hasura_secret_key
  graphql-gateway:
    image: platyplus/graphql-gateway
    depends_on:
      - authentication
      - graphql-engine
      - functions
    environment:
      HASURA_URL: 'http://graphql-engine:3000/v1alpha1/graphql'
      AUTH_URL: 'http://authentication:3000/graphql'
      FUNCTIONS_URL: 'http://functions:3000/graphql'
      NODE_ENV: production
      HASURA_GRAPHQL_ADMIN_SECRET_FILE: /run/secrets/hasura_secret_key
      PUBLIC_KEY_FILE: /run/secrets/authentication_public_key
    labels:
      - 'traefik.frontend.rule=Host:api.${DOMAIN}'
      - traefik.port=3000
    deploy:
      replicas: 1
    secrets:
      - authentication_public_key
      - hasura_secret_key
  graphql-engine:
    image: platyplus/graphql-engine
    depends_on:
      - authentication
      - postgres
      - synchronization-hook
    deploy:
      replicas: 1
    environment:
      HASURA_GRAPHQL_ADMIN_SECRET_FILE: /run/secrets/hasura_secret_key
    secrets:
      - authentication_public_key
      - hasura_secret_key
  postgres:
    image: 'mdillon/postgis:11-alpine'
    volumes:
      - 'db_data:/var/lib/postgresql/data'
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U postgres
      interval: 30s
      timeout: 5s
  reverse-proxy:
    image: traefik
    command:
      - '--docker.watch'
      - '--docker'
      - '--web'
    ports:
      - '80:80'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
    healthcheck:
      test:
        - CMD
        - /traefik
        - healthcheck
        - '--ping'
      interval: 30s
      timeout: 5s
  synchronization-hook:
    image: platyplus/synchronization-hook
    environment:
      HASURA_URL: 'http://graphql-engine:3000/v1alpha1/graphql'
      HASURA_GRAPHQL_ADMIN_SECRET_FILE: /run/secrets/hasura_secret_key
      NODE_ENV: production
    deploy:
      replicas: 1
    secrets:
      - hasura_secret_key
volumes:
  db_data: null
secrets:
  authentication_private_key:
    external: true
  authentication_public_key:
    external: true
  hasura_secret_key:
    external: true
