version: '3.1'
services:
  app:
    image: platyplus/platyplus
    depends_on:
      - graphql-engine
    environment:
      API: 'graphql.${DOMAIN}/v1alpha1/graphql'
    labels:
      - 'traefik.frontend.rule=Host:app.${DOMAIN}'
      - traefik.port=80
  authentication:
    image: platyplus/authentication
    depends_on:
      - postgres
    environment:
      ALGORITHM: RS256
      HASURA_URL: 'http://graphql-engine:3000/v1alpha1/graphql'
      HASURA_GRAPHQL_ACCESS_KEY_FILE: /run/secrets/hasura_secret_key
      NODE_ENV: production
      PRIVATE_KEY_FILE: /run/secrets/authentication_private_key
      PUBLIC_KEY_FILE: /run/secrets/authentication_public_key
    deploy:
      replicas: 1
    secrets:
      - authentication_private_key
      - authentication_public_key
      - hasura_secret_key
  graphql-engine:
    image: platyplus/graphql-engine
    depends_on:
      - authentication
      - postgres
    environment:
      HASURA_GRAPHQL_SERVER_PORT: 3000
      HASURA_GRAPHQL_DATABASE_URL: 'postgres://postgres:@postgres:5432/postgres'
      AUTH_ALGORITHM: RS256
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: anonymous
      HASURA_GRAPHQL_MIGRATIONS_DIR: migrations
      HASURA_GRAPHQL_ENABLE_CONSOLE: false
      AUTH_PUBLIC_KEY_FILE: /run/secrets/authentication_public_key
      HASURA_GRAPHQL_ACCESS_KEY_FILE: /run/secrets/hasura_secret_key
    labels:
      - 'traefik.frontend.rule=Host:graphql.${DOMAIN}'
      - traefik.port=3000
    deploy:
      replicas: 1
    secrets:
      - authentication_public_key
      - hasura_secret_key
  postgres:
    image: 'mdillon/postgis:11-alpine'
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U postgres
      interval: 30s
      timeout: 5s
    volumes:
      - 'db_data:/var/lib/postgresql/data'
  reverse-proxy:
    image: traefik
    command:
      - '--docker.watch'
      - '--docker'
      - '--web'
    healthcheck:
      test:
        - CMD
        - /traefik
        - healthcheck
        - '--ping'
      interval: 30s
      timeout: 5s
    ports:
      - '80:80'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
  synchronization-hook:
    image: platyplus/synchronization-hook
    depends_on:
      - graphql-engine
    environment:
      HASURA_URL: 'http://graphql-engine:3000/v1alpha1/graphql'
      HASURA_GRAPHQL_ACCESS_KEY_FILE: /run/secrets/hasura_secret_key
      NODE_ENV: production
    deploy:
      replicas: 1
    secrets:
      - hasura_secret_key
volumes:
  db_data: null
secrets:
  authentication_private_key:
    external: true
  authentication_public_key:
    external: true
  hasura_secret_key:
    external: true
