FROM node:12-alpine
RUN yarn global add @platyplus/functions-service

ARG GRAPHQL_ENGINE_URL=http://graphql-engine:8080
ENV GRAPHQL_ENGINE_URL $GRAPHQL_ENGINE_URL
ENV AUTHENTICATION_URL=http://authentication:3000

# TODO: algo in the template?
ARG ALGORITHM=RS256
ENV ALGORITHM $ALGORITHM

USER node
EXPOSE 3000
CMD ["functions-service"]