FROM node:12-alpine
ARG GRAPHQL_ENGINE_URL=http://graphql-engine:8080
ENV GRAPHQL_ENGINE_URL $GRAPHQL_ENGINE_URL

RUN yarn global add @platyplus/authentication-service
USER node
EXPOSE 3000
CMD ["authentication-service"]