# * Not using node-alpine as it does not support glibc, that is required by pg-query-parser. Not using node-slim either as pg-query-parser requires node-gyp to be built, therefore python etc
FROM node:12
RUN yarn global add @platyplus/metadata-service

# ! Required by node-pg-query-native
# TODO test if it is absolutely required. If not, test with node-slim
RUN yarn global add node-gyp && cd node_modules/pg-query-native && node-gyp rebuild

USER node
EXPOSE 3000
CMD ["metadata-service"]