#!/usr/bin/env node

const app = require('/opt/app/index'),
  PORT = process.env.PORT || 3000,
  http = require('http'),
  { createTerminus } = require('@godaddy/terminus')

// Checks whether this is a Koa App or an Express app TODO: test
const appKoaExpress = app.callback ? app.callback() : app
var server = http.createServer(appKoaExpress)
server.listen(PORT, () => {
  console.log(`🚀 Server ready and listening on port ${PORT}`)
})

// Health check
function onSignal () {
  console.info(
    'Got SIGINT (aka ctrl-c in docker). Graceful shutdown ',
    new Date().toISOString()
  )
}
function onShutdown () {
  console.info('cleanup finished, server is shutting down')
}
function healthCheck () {
  return Promise.resolve(200)
}
const terminusOptions = {
  // healthcheck options
  healthChecks: {
    '/healthcheck': healthCheck // a promise returning function indicating service health
  },
  timeout: 1000, // [optional = 1000] number of milliseconds before forcefull exiting
  onSignal, // [optional] cleanup function, returning a promise (used to be onSigterm)
  onShutdown // [optional] called right before exiting
}
createTerminus(server, terminusOptions)
