name: Commit on master branch

on:
  push:
    branches:
      - master
# on:
#   pull_request:
#     branches:
#       - master
#   push:
#     branches:
#       - master

jobs:
  packages-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn install
  # TODO run tests
      
  docker-build:
    needs: packages-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn run ci:docker build
        env:
          IMG_PREFIX: gcr.io/${{secrets.gcloud_project_id}}
      - run: yarn run ci:docker deploy
        env:
          IMG_PREFIX: gcr.io/${{secrets.gcloud_project_id}}
  # TODO deploy on staging
      
