name: Publish the NPM packages

on:
  release:
    types: [published]

# on:
#   pull_request:
#     branches:
#       - master
#   push:
#     branches:
#       - master

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: yarn install
      - run: echo "registry=https://registry.npmjs.org/" > .npmrc
      - run: echo "//registry.npmjs.org/:_authToken=${{secrets.npm_token}}" >> .npmrc
      - run: cat .npmrc
      - run: yarn run publish
      
