name: Node.js Package

on:
  release:
    types: [published]

# on:
#   pull_request:
#     branches:
#       - master
#   push:
#     branches:
#       - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn global add lerna
      - run: lerna bootstrap

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: lerna publish from-git
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}

